language: python
python:
  - "2.7"
env:
  - DJANGO=1.6
  - DJANGO=1.7
  - DJANGO=1.8
services:
  - mongodb
install:
  - "pip install -r requirements.txt"
script:
  - coverage run --source=time_logger setup.py test
after_success:
  - coveralls